version: '3'


services:
  smallingo-redis:
    container_name: smallingo-redis
    image: redis:latest
    ports:
      - "6379:6379"

  smallingo-backend:
    container_name: smallingo-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - smallingo-redis

  smallingo-frontend:
    container_name: smallingo-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules

volumes:
  postgres_data:
