version: '3'

services:
  smallingo-postgres:
    container_name: smallingo-postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  smallingo-backend:
    container_name: smallingo-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - smallingo-postgres

  smallingo-frontend:
    container_name: smallingo-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules


volumes:
  postgres_data:
