version: '3'

services:
  smallingo-postgres:
    container_name: smallingo-postgres
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  smallingo-backend:
    container_name: smallingo-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - smallingo-postgres

volumes:
  postgres_data:
