# Generated by Django 5.0.3 on 2024-03-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmallingoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=65535)),
                ('duration', models.DurationField(null=True)),
                ('pixels_tall', models.PositiveIntegerField(null=True)),
                ('audio_fragment', models.FileField(null=True, upload_to='')),
                ('audio_fragment_text', models.TextField(null=True)),
                ('audio_fragment_speech', models.FileField(null=True, upload_to='')),
                ('video_thumbnail', models.ImageField(null=True, upload_to='')),
                ('video_ocr', models.TextField(null=True)),
            ],
        ),
    ]
