# Generated by Django 5.0.3 on 2024-03-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smallingovideo_audio_fragment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallingovideo',
            name='audio_fragment',
            field=models.FileField(blank=True, null=True, upload_to='original_audio'),
        ),
        migrations.AlterField(
            model_name='smallingovideo',
            name='audio_fragment_speech',
            field=models.FileField(blank=True, null=True, upload_to='translation_audio'),
        ),
        migrations.AlterField(
            model_name='smallingovideo',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
