# Generated by Django 5.0.3 on 2024-03-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_smallingovideo_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallingovideo',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='original_video'),
        ),
    ]
