# Generated by Django 5.0.3 on 2024-03-08 09:42

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_smallingovideo_audio_fragment_and_more'),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SUPERUSER_USERNAME=os.environ.get("DJANGO_SUPERUSER_USERNAME")
        DJANGO_SUPERUSER_EMAIL=os.environ.get("DJANGO_SUPERUSER_EMAIL")
        DJANGO_SUPERUSER_PASSWORD=os.environ.get("DJANGO_SUPERUSER_PASSWORD")

        if any([not DJANGO_SUPERUSER_USERNAME, not DJANGO_SUPERUSER_EMAIL, not DJANGO_SUPERUSER_PASSWORD]):
            raise ValueError("Some required parameters where empty")

        superuser = User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            email=DJANGO_SUPERUSER_EMAIL,
            password=DJANGO_SUPERUSER_PASSWORD
        )

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser)
    ]
