# Generated by Django 5.0.3 on 2024-03-10 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_smallingovideo_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallingovideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
